---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{id}":
    get:
      summary: Retrieve a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  photo:
                    type: string
                  bio:
                    type: string
                  postsCounter:
                    type: integer
                required:
                - id
                - name
                - postsCounter
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
